name: NEPSE Market Sync

on:
  repository_dispatch:
    # This matches the 'event_type' from your Render FastAPI code
    types: [trigger_nepse_sync]
  
  schedule:
    # Runs every hour from 11 AM to 3 PM Nepal Time
    # 05:15 UTC = 11:00 NPT
    # 09:15 UTC = 15:00 NPT
    # Days: 1-5 (Monday, Tuesday, Wednesday,Thrusday, Friday)
    - cron: '15 5-9 * * 0-3'

jobs:
  scrape_and_update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install requests sqlalchemy psycopg2-binary pandas pytz

      - name: Execute Scraper Script
        env:
          # Using your specific secret name
          DATABASE_URL: ${{ secrets.NEON_DATABASE_URL }}
        run: python Utility/Refresh.py
